### PR TITLE
Removed duplicates with references

### PR DESCRIPTION
**Pull request by angelakdang**
fatal-police-shootings-data.csv has been updated with duplicates (TK TK entries ignored).

Code to remove the duplicates is remove_duplicates.py with references to news articles that indicate which record was chosen.

### CODE REVIEW

**Comment by JohnDovey** [comment]
Awesome

**Comment by SpyderRivera** [comment]
LGTM

**Comment by angelakdang** [comment]
@jmuyskens Would you be the person to do the merge?

**Comment by jmuyskens** [comment]
This has been resolved by 4b61f9a25982d587deacd4f83272f43d701321b8 and b3ebc7cdd68fc33cc72d5d514e78a568b12ec37f. Note that we are not merging PRs because the CSV in this repo is published downstream of our internal database.

**Pull request closed without merging**
